name: Run tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3
    - name: Run tests
      run: |
        python3 scripts/test.py
